add $r2, $zero, $imm, 1		# PC=0  (Core ID = 1)
add $r5, $zero, $imm, 128	# PC=1  (Max Loop Count = 128)
add $r6, $zero, $zero, 0	# PC=2  (i = 0)
lw $r9, $imm, $zero, 1		# PC=3  (LOOP_START: Load Turn from Mem[1])
bne $imm, $r2, $r9, 4		# PC=4  (If MyID != Turn, Jump to PC=3)
lw $r9, $imm, $zero, 1      # PC=5  (Reload Turn)
lw $r10, $zero, $zero, 0	# PC=6  (Load Counter from Mem[0])
add $r10, $r10, $imm, 1		# PC=7  (Counter++)
sw $r10, $zero, $zero, 0	# PC=8  (Store Counter to Mem[0])
add $r9, $zero, $imm, 2		# PC=9  (Next Turn = 2)
add $r6, $r6, $imm, 1		# PC=10 (i++)
bne $imm, $r6, $r5, 3		# PC=11 (If i != 128, Jump to PC=3)
sw $r9, $imm, $zero, 1		# PC=12  (Store Turn to Mem[1])
halt $zero, $zero, $zero, 0	# PC=14